CI: try to make push of flake-update to main work
It currently fails with

```
 ! [rejected]        HEAD -> main (fetch first)
error: failed to push some refs to 'https://github.com/marienz/nix-doom-emacs-unstraightened'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.
```

Our local checkout is shallow. Assume we can fix this by fetching just
the parent of the commit we want to push, which should be the commit
origin/main points at.